### PR TITLE
Added Support for AWS EC2 Reserved Instances

### PR DESCRIPTION
**Pull request by kedarghule**
This PR will add support for EC2 Reserved Instances and populate them in the graph DB.

Futhermore, it also solves an issue highlighted in https://github.com/lyft/cartography/pull/603#issuecomment-818457347

### CODE REVIEW

**Comment by kedarghule** [comment]
cc: @marco-lancini  , @mpurusottamc

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
Can you add some color to why `get_botocore_config` is not needed? I don't see retries and timeouts being specified elsewhere. I could imagine a PR to replace that and set env vars as a separate thing, however.

Otherwise, looks good.

**Comment by kedarghule** [comment]
> Can you add some color to why `get_botocore_config` is not needed? I don't see retries and timeouts being specified elsewhere. I could imagine a PR to replace that and set env vars as a separate thing, however.
> 
> Otherwise, looks good.

It builds on the discussion @achantavy  and @mpurusottamc had in the PR - https://github.com/lyft/cartography/pull/603

**Comment by mpurusottamc** [comment]
@FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg As Kedar has referenced the PR #603, the goal is to get rid of these functions and use environment variables instead. That's in our roadmap as well. 

Let us know if this is a blocker to approve the PR.

**Review by achantavy — CHANGES_REQUESTED** [review]
> I could imagine a PR to replace that and set env vars as a separate thing, however.

I agree. @kedarghule Can you please move the `get_botocore_config` changes to a separate PR? After that any of us can approve; the code looks otherwise good to me.

**Comment by kedarghule** [comment]
> > I could imagine a PR to replace that and set env vars as a separate thing, however.
> 
> I agree. @kedarghule Can you please move the `get_botocore_config` changes to a separate PR? After that any of us can approve; the code looks otherwise good to me.

@achantavy Alright. I have removed those changes from this PR. You may take a quick look and then approve :)
cc: @mpurusottamc and @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg

**Review by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg — APPROVED** [review]
Looks great, thanks!

**Review by achantavy — APPROVED** [review]

**Pull request merged**
