### PR TITLE
AWS: Tags: improve logging, cleanup old dangling tags

### PR DESCRIPTION
**Pull request by ramonpetgrave64**
This PR 
* improves logging: account id and tag load count #772 
* adds the RETURN COUNT(*) to the AWSTag cleanup job, so that we can begin collecting its metrics
* removes old, unattached AWSTag nodes that may have been attached to resources that no longer exist

### CODE REVIEW

**Comment by ramonpetgrave64** [comment]
@ryan-lane Have a look, please.

**Review by ryan-lane — APPROVED** [review]

**Comment by ryan-lane** [comment]
Looks good!

**Comment by ramonpetgrave64** [comment]
> Looks good!

Thanks! I did change one thing: [(n)--(n) to (n)<-[:TAGGED]-()](https://github.com/lyft/cartography/pull/802/commits/92064dc807cf52c4dca4ae292fa00225b6a5a69a)

**Review by zoe-lyft — APPROVED** [review]

**Comment by ramonpetgrave64** [comment]
> Looks good!

Thanks!

**Pull request merged**
