### PR TITLE
#842 s3 exception fix

### PR DESCRIPTION
**Pull request by krisek**
This is a rudimentary fix for #842, unfortunately I have no time to update tests or tidy up more, feel free to take it or leave it.

### CODE REVIEW

**Comment by krisek** [comment]
As usual, some tests fail for files which I didn't touch at all... it's all a mystery.

**Comment by ryan-lane** [comment]
@krisek these test failures are related to your changes, and are lint failures that can be automatically fixed by running pre-commit locally. Can you please run that?

**Comment by achantavy** [comment]
Hey @krisek, good to hear from you again. You can use `make test_lint` locally before pushing to catch this stuff before the CI complains. Looks like it doesn't like some paren stuff: https://github.com/lyft/cartography/runs/6430113666?check_suite_focus=true

**Comment by achantavy** [comment]
Per https://github.com/lyft/cartography/issues/842#issuecomment-1125028860, I think it makes more sense to add IllegalLocationConstraints to common exceptions. If the issue persists then we can use this PR instead.

**Pull request closed without merging**
