### PR TITLE
fixed typo in Azure load_vms cypher

### PR DESCRIPTION
**Pull request by amirjalali65**

### CODE REVIEW

**Comment by achantavy** [comment]
Thanks for the fix! Can you please sign the CLA?

**Comment by amirjalali65** [comment]
I've already signed the CLA. Seems the check needs to be retriggered.

**Comment by ramonpetgrave64** [comment]
@amirjalali65 It looks like the commit you authored doesn't have your actual github name associated with the commit. You'll need to setup your git config
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

**Comment by ramonpetgrave64** [comment]
@amirjalali65 Some of the commits still have the wrong author, so you'll need to rebase/squash and maybe do a force-push.
https://github.com/lyft/cartography/pull/1047/commits

**Comment by ramonpetgrave64** [comment]
Looks good. 
Docs here: https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.models.osprofile?view=azure-python

**Review by chandanchowdhury — APPROVED** [review]

**Comment by achantavy** [comment]
@amirjalali65 Wow, how did we miss this one for so long haha, sorry for the delay and thank you for the contribution!

@chandanchowdhury - thank you for spotting this!

**Pull request merged**
