### PR TITLE
Update install docs to reference intel module docs

### PR DESCRIPTION
**Pull request by ryan-lane**
Pointing to the modules documentation, from the install document, leads to a blank page, as the actual configuration documentation for each module is within the module's docs. This change updates the docs to tell readers to visit the docs in each relevant intel module.

### CODE REVIEW

**Comment by ramonpetgrave64** [comment]
@ryan-lane I think it's better to link to original docs for now.
https://github.com/lyft/cartography/tree/master/docs/setup/config

**Comment by ramonpetgrave64** [comment]
@ryan-lane I think it's better to link to original docs for now.
https://github.com/lyft/cartography/tree/master/docs/setup/config

**Review by achantavy — APPROVED** [review]
This looks good to me, the current link (https://lyft.github.io/cartography/modules/index.html) points to an empty page. Thanks @ryan-lane.

**Comment by achantavy** [comment]
@ryan-lane can you update the branch so we can merge it in?

**Comment by ryan-lane** [comment]
Done!

**Pull request merged**
