### PR TITLE
Refactor EC2 Volume to allow optional properties.

### PR DESCRIPTION
**Pull request by andrew-womeldorf**
The existing EC2 Volume transformation assumes all properties will be present. See [EC2 API Reference for Volumes](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Volume.html) to see that all properties on the Volume are optional.

### CODE REVIEW

**Comment by andrew-womeldorf** [comment]
FYI - getting a 403 when attempting to open the CLA

**Comment by achantavy** [comment]
Thanks for the PR, makes sense to me. I'll check on the CLA tool on Monday.

**Comment by achantavy** [comment]
@andrew-womeldorf - ok, CLA check is working now, can you sign?

**Comment by andrew-womeldorf** [comment]
Yes, it works now. Signed!

**Review by achantavy — APPROVED** [review]

**Comment by achantavy** [comment]
Thank you!

**Pull request merged**
