### PR TITLE
#559 - Update AWS docs on using environment vars for retry behavior

### PR DESCRIPTION
**Pull request by mpurusottamc**
Added AWS Config with retry logic to fetch API Gateway resources. We have tested it on our own service deployment.

https://github.com/lyft/cartography/issues/559

cc: @cpollard0

### CODE REVIEW

**Review by achantavy — CHANGES_REQUESTED** [review]
Thanks for taking this on! Could we use or modify https://github.com/lyft/cartography/blob/1583dbe6e08ad5402012714db9b2a652506f2b76/cartography/intel/aws/ec2/util.py#L5 instead?

**Comment by cpollard0** [comment]
Have we considered using the AWS_MAX_ATTEMPTS environment variable, having boto3 pick it up, and not setting it in code? End users can use the setting that's best for them, and we could update the readme to give some guidance on how to and best practices. It'll also affect all clients, so no need to set and maintain it in a ton of places.

**Comment by achantavy** [comment]
@cpollard0 Hm, good point actually. I wasn't actually aware of that. We should update documentation instead on boto3 config information available: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables

**Comment by mpurusottamc** [comment]
@achantavy @cpollard0 I like the idea to use environment variables instead of assigning a static value. I can update the documentation with this information.

I see another instance of similar code at https://github.com/lyft/cartography/blob/master/cartography/intel/aws/elasticsearch.py#L41
`https://github.com/lyft/cartography/blob/master/cartography/intel/aws/elasticsearch.py#L41`

We should standardize to have just one set of config in the AWS intel root, instead of inside EC2 folder. What do you guys think?

**Comment by achantavy** [comment]
> I can update the documentation with this information.

Thank you!

> We should standardize to have just one set of config in the AWS intel root, instead of inside EC2 folder. What do you guys think?

The fully correct solution would be to encourage using the env vars instead  and eventually remove these functions completely (can come in a future PR)

**Comment by mpurusottamc** [comment]
@achantavy i have updated the docs

**Review by achantavy — APPROVED** [review]
Thank you!

**Pull request merged**
