### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by ramonpetgrave64**
Adds some guidance on how to edit/create intel modules

### CODE REVIEW

**Comment by resilience-jychp** [comment]
@ramonpetgrave64 may you can add :
- edit cli.py
- edit config.py
- add module description on READEME.md

May be you can refer to @achantavy Google Doc or add some precisions about auto cleanup (only Node with sub-resource link will be deleted)

May be adding a link to analysis jobs can be helpful too.

A bit out of scope but a detailed exemple of transform with n to n cardinality will be useful.

This template will be helpful.

**Comment by achantavy** [comment]
> edit cli.py
> edit config.py
> add module description on READEME.md
> May be you can refer to @achantavy Google Doc or add some precisions about auto cleanup (only Node with sub-resource link will be deleted)
> May be adding a link to analysis jobs can be helpful too.
> A bit out of scope but a detailed exemple of transform with n to n cardinality will be useful.

This is very good documentation feedback, thank you.

Regarding the pull request template, I think a long list like this would do better in the [how to write an intel module guide](https://lyft.github.io/cartography/dev/writing-intel-modules.html) instead of this checklist.

I think we should keep a pull request template to roughly 5 items max. This is meant to remind a contributor of things they might have missed, not show them how to do everything.

**Comment by ramonpetgrave64** [comment]
@achantavy @resilience-jychp Thanks. I've shortened it

**Comment by resilience-jychp** [comment]
@ramonpetgrave64 may be you can add a reminder for "extra-index" in your checklist

**Comment by chandanchowdhury** [comment]
* Create or update schema docs under `docs/root/modules/`.

**Review by achantavy — APPROVED** [review]

**Pull request merged**
