### PR TITLE
Added ZeusCloud as list of companies using cartography

### PR DESCRIPTION
**Pull request by surendrapathak**
Details: https://github.com/Zeus-Labs/ZeusCloud

### CODE REVIEW

**Comment by achantavy** [comment]
🎉 -- will be able to get the CLA thing early next week hopefully

**Comment by surendrapathak** [comment]
@achantavy Sounds good. Let me know if I need to change anything. I tried to follow the CLA acceptance but ended up at a dead-end. Happy to change the PR as needed.

**Comment by achantavy** [comment]
@surendrapathak - ok, CLA is working now, can you sign?

**Comment by surendrapathak** [comment]
@achantavy Looks like CLA is cleared now.

**Review by achantavy — APPROVED** [review]

**Pull request merged**
