### PR TITLE
Fix query for gcp firewall ingress deny rules.

### PR DESCRIPTION
**Pull request by ramonpetgrave64**
The bug happens whenever there are existing rules in both `fw['transformed_allow_list']` and in `fw['transformed_deny_list']`. In that case, both of the sub-queries creating the realtionships `[r:ALLOWED_BY]` and `[r:DENIED_BY]` would have been added to the main `query` string, causing and error. This could be related to the error mentioned in #183 .

I haven't tested this yet, but I believe this should fix it.

### CODE REVIEW

**Comment by achantavy** [comment]
Thanks very much for getting started on this.  I think that using an approach like #181 might be a very clean way to parameterize the relationship type of ALLOWED_BY and DENIED_BY, would you consider doing it that way?

**Comment by marco-lancini** [comment]
Hi! I hope this is not going to be closed, as at the moment Cartography crashes when this condition is verified (as mentioned in #183)

**Comment by achantavy** [comment]
I'll do some internal testing on this later on and report back.

**Comment by ramonpetgrave64** [comment]
Okay. This fix also seems to deal with issue #183 . Still not sure why. 

I had trouble testing, since I don't have GCP Organization set up with my personal account, so I did a hacky workaround for that.

Also did the subquery replacement with `Template`, as @achantavy suggested.

**Comment by marco-lancini** [comment]
Hello! :wave: 
I can confirm I just tested this diff and it does solve issue #183! :tada:

**Comment by achantavy** [comment]
Sorry again for how long this has taken.  My test run of this PR has started right now; will report back.

**Comment by ramonpetgrave64** [comment]
We should probably also add test cases for this, too.

**Comment by achantavy** [comment]
Ah right, since the [existing test](https://github.com/lyft/cartography/blob/e2d7a626ba29df30ff308a9d3c311b297a7c8d30/tests/integration/cartography/intel/gcp/test_compute.py#L336) only checks for `ALLOWED_BY`.

**Comment by marco-lancini** [comment]
@achantavy: would it be possible to push a minor release of Cartography, so to include this fix into the PyPi package (https://pypi.org/project/cartography/)?

**Comment by achantavy** [comment]
@marco-lancini On it, sorry for delays.

**Comment by achantavy** [comment]
Alright done.

**Pull request merged**
