### PR TITLE
Add missing attributes to AWSIpv6CidrBlock

### PR DESCRIPTION
**Pull request by aashishgaba-cn**
Fix: #515 

Adds the following attributes to the AWSIpv6CidrBlock
- ipv6_pool
- network_border_group

### CODE REVIEW

**Review by achantavy — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you please also update https://github.com/lyft/cartography/blob/master/docs/schema/aws.md#awsvpc?

**Comment by aashishgaba-cn** [comment]
I've updated the schema. PTAL
Thanks

**Comment by achantavy** [comment]
Hi @aashishgaba-cn, can you please sign the CLA? If you have already, double check that each commit was made with the email address used to sign the CLA.

Also, have you tested this change in your own setup?

**Comment by aashishgaba-cn** [comment]
Hi @achantavy,  my bad, I forgot to sign it earlier.

Yes, I've tested the changes in my own setup and it's adding those two fields in the `AWSIpv6CidrBlock`

**Comment by achantavy** [comment]
@aashishgaba-cn, can you please merge in the latest master and repush to this branch? For some reason I'm not able to do this on this PR.

**Comment by achantavy** [comment]
@aashishgaba-cn - closing this since it has the checks from our old CI. Can you please resubmit?

**Pull request closed without merging**
