### PR TITLE
#231, #258: Only sync AWS regions that we are opted in for or don't require opt-in 

### LINKED ISSUE #231: S3 buckets in `me-south-1` region fails with IllegalLocationConstraintException
*Title*: S3 buckets in `me-south-1` region fails with IllegalLocationConstraintException

*Description*:
Initial sync fails when scanning a bucket in `me-south-1` region

*To Reproduce*:
Create S3 bucket in `me-south-1` I suspect, but I don't have another account to test with at the moment.

*Logs*:
```
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cartography/cli.py", line 216, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.6/site-packages/cartography/cli.py", line 196, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.6/site-packages/cartography/sync.py", line 135, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.6/site-packages/cartography/sync.py", line 69, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 106, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, regions, config.update_tag, common_job_parameters)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 44, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, regions, sync_tag, common_job_parameters)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 22, in _sync_one_account
    s3.sync(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 326, in sync
    load_s3_details(neo4j_session, acl_and_policy_data_iter, current_aws_account_id, aws_update_tag)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 136, in load_s3_details
    for bucket, acl, policy in s3_details_iter:
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 26, in get_s3_bucket_details
    acl = get_acl(bucket, client)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 54, in get_acl
    acl = client.get_bucket_acl(Bucket=bucket['Name'])
  File "/Users/drosenbloom/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 272, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/drosenbloom/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 576, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the GetBucketAcl operation: The me-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```
*Please complete the following information:*:
>  - Cartography release version: 0.15.0
>  - Python version: 3.6.6
>  - OS: OSX 10.4.6 (probably unrelated)

*Additional context*:
> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by achantavy**
Fixes #231, #258.

### CODE REVIEW

**Comment by marco-lancini** [comment]
Doesn't seem to solve the issue for me:

```
INFO:cartography.intel.aws:Syncing AWS account with ID '<redacted>' using configured profile 'router'.                                                    
INFO:cartography.intel.aws.iam:Syncing IAM for account '<redacted>'.                                                                
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'eu-north-1'.                                                                 
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'ap-south-1'.                                                                 
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'eu-west-3'.                                                                  
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'eu-west-2'.                                                                  
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'eu-west-1'.                                                                  
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'ap-northeast-2'.                                                             
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'ap-northeast-1'.                                                             
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'sa-east-1'.
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'ca-central-1'.
INFO:cartography.intel.aws.s3:Syncing S3 for account '<redacted>' in region 'ap-east-1'.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/app/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "/app/cartography/util.py", line 58, in timed
    return method(*args, **kwargs)
 File "/app/cartography/intel/aws/__init__.py", line 114, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "/app/cartography/intel/aws/__init__.py", line 64, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/app/cartography/intel/aws/__init__.py", line 38, in _sync_one_account
    s3.sync(neo4j_session, boto3_session, regions, account_id, sync_tag, common_job_parameters)
  File "/app/cartography/util.py", line 58, in timed
    return method(*args, **kwargs)
  File "/app/cartography/intel/aws/s3.py", line 336, in sync
    bucket_data = get_s3_bucket_list(boto3_session, region)
  File "/app/cartography/util.py", line 58, in timed
    return method(*args, **kwargs)
  File "/app/cartography/intel/aws/s3.py", line 19, in get_s3_bucket_list
    return client.list_buckets()
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidToken) when calling the ListBuckets operation: The provided token is malformed or otherwise invalid.
```

**Comment by achantavy** [comment]
@marco-lancini Can you try the Dynamo sync by itself and see if that also gives an InvalidToken exception?

**Comment by marco-lancini** [comment]
> @marco-lancini Can you try the Dynamo sync by itself and see if that also gives an InvalidToken exception?

Same result when running only the Dynamo sync by itself

**Comment by marco-lancini** [comment]
Ok this is even more odd:
```
{'Endpoint': 'ec2.ap-east-1.amazonaws.com',
 'OptInStatus': 'opted-in',
 'RegionName': 'ap-east-1'}
```

**Comment by achantavy** [comment]
@flyinbutrs, @anewton1980: can you please give this fix a try? I don't have any regions to test this with.

**Comment by marco-lancini** [comment]
> @flyinbutrs, @anewton1980: can you please give this fix a try? I don't have any regions to test this with.

Hi! Any luck with this?

**Comment by anewton1980** [comment]
Apologies for the slow reply.

I have tested this morning and still get an error

RROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\cartography\sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 115, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 65, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 25, in _sync_one_account
    s3.sync(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 340, in sync
    load_s3_details(neo4j_session, acl_and_policy_data_iter, current_aws_account_id, aws_update_tag)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 144, in load_s3_details
    for bucket, acl, policy in s3_details_iter:
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 29, in get_s3_bucket_details
    acl = get_acl(bucket, client)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 59, in get_acl
    acl = client.get_bucket_acl(Bucket=bucket['Name'])
  File "c:\python38\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python38\lib\site-packages\botocore\client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the GetBucketAcl operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.
Traceback (most recent call last):
  File "C:\Python38\Scripts\cartography-script.py", line 11, in <module>
    load_entry_point('cartography==0.20.0', 'console_scripts', 'cartography')()
  File "c:\python38\lib\site-packages\cartography\cli.py", line 297, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "c:\python38\lib\site-packages\cartography\cli.py", line 277, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "c:\python38\lib\site-packages\cartography\sync.py", line 145, in run_with_config
    return sync.run(neo4j_driver, config)
  File "c:\python38\lib\site-packages\cartography\sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 115, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 65, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 25, in _sync_one_account
    s3.sync(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 340, in sync
    load_s3_details(neo4j_session, acl_and_policy_data_iter, current_aws_account_id, aws_update_tag)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 144, in load_s3_details
    for bucket, acl, policy in s3_details_iter:
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 29, in get_s3_bucket_details
    acl = get_acl(bucket, client)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 59, in get_acl
    acl = client.get_bucket_acl(Bucket=bucket['Name'])
  File "c:\python38\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python38\lib\site-packages\botocore\client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the GetBucketAcl operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.

**Comment by achantavy** [comment]
Hey @anewton1980, can you please share the output of `aws ec2 describe-regions`? I'm interested in seeing what your value for `"OptInStatus":` on `ap-east-1` is.

Also, feel free to `@` me on Slack - might be faster to talk there.

**Comment by anewton1980** [comment]
> Hey @anewton1980, can you please share the output of `aws ec2 describe-regions`? I'm interested in seeing what your value for `"OptInStatus":` on `ap-east-1` is.
> 
> Also, feel free to `@` me on Slack - might be faster to talk there.

output below
{
    "Regions": [
        {
            "Endpoint": "ec2.eu-north-1.amazonaws.com",
            "RegionName": "eu-north-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ap-south-1.amazonaws.com",
            "RegionName": "ap-south-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.eu-west-3.amazonaws.com",
            "RegionName": "eu-west-3",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.eu-west-2.amazonaws.com",
            "RegionName": "eu-west-2",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.eu-west-1.amazonaws.com",
            "RegionName": "eu-west-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ap-northeast-2.amazonaws.com",
            "RegionName": "ap-northeast-2",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ap-northeast-1.amazonaws.com",
            "RegionName": "ap-northeast-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.sa-east-1.amazonaws.com",
            "RegionName": "sa-east-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ca-central-1.amazonaws.com",
            "RegionName": "ca-central-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ap-east-1.amazonaws.com",
            "RegionName": "ap-east-1",
            "OptInStatus": "opted-in"
        },
        {
            "Endpoint": "ec2.ap-southeast-1.amazonaws.com",
            "RegionName": "ap-southeast-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ap-southeast-2.amazonaws.com",
            "RegionName": "ap-southeast-2",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.eu-central-1.amazonaws.com",
            "RegionName": "eu-central-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.us-east-1.amazonaws.com",
            "RegionName": "us-east-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.us-east-2.amazonaws.com",
            "RegionName": "us-east-2",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.us-west-1.amazonaws.com",
            "RegionName": "us-west-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.us-west-2.amazonaws.com",
            "RegionName": "us-west-2",
            "OptInStatus": "opt-in-not-required"
        }
    ]
}

**Comment by marco-lancini** [comment]
Might be worth noticing the error @anewton1980 is getting:

```
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the GetBucketAcl operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```

is different from the one I am getting:

```
botocore.exceptions.ClientError: An error occurred (InvalidToken) when calling the ListBuckets operation: The provided token is malformed or otherwise invalid.
```

**Comment by achantavy** [comment]
@anewton1980 Just to double check, what commit hash are you running? It should be 6be6f9077265e3604c61b85f3450a313520955b6.

**Comment by anewton1980** [comment]
> @anewton1980 Just to double check, what commit hash are you running? It should be [6be6f90](https://github.com/lyft/cartography/commit/6be6f9077265e3604c61b85f3450a313520955b6).

I have just downloaded that version to check i was running the correct version and get the error below

ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\cartography\sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 115, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 65, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\intel\aws\__init__.py", line 25, in _sync_one_account
    s3.sync(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 340, in sync
    load_s3_details(neo4j_session, acl_and_policy_data_iter, current_aws_account_id, aws_update_tag)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 144, in load_s3_details
    for bucket, acl, policy in s3_details_iter:
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 29, in get_s3_bucket_details
    acl = get_acl(bucket, client)
  File "c:\python38\lib\site-packages\cartography\util.py", line 58, in timed
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\cartography\intel\aws\s3.py", line 59, in get_acl
    acl = client.get_bucket_acl(Bucket=bucket['Name'])
  File "c:\python38\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python38\lib\site-packages\botocore\client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the GetBucketAcl operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.

**Comment by marco-lancini** [comment]
Seems related to https://github.com/aws/aws-cli/issues/4445, which, in turn, is a duplicate of https://github.com/boto/boto3/issues/2098:

> If a request arrives at the wrong Amazon S3 location, Amazon S3 responds with a temporary redirect that tells the requester to resend the request to a new endpoint. If a request is incorrectly formed, Amazon S3 uses permanent redirects to provide direction on how to perform the request correctly. Here is the link which demonstrates how s3 redirect behavior works:
https://docs.aws.amazon.com/AmazonS3/latest/dev/Redirects.html

Apparently they accepted the following as a "fix":

```
client = boto3.client('s3',region_name=location)
```

**Comment by rsclarke-vgw** [comment]
Just an observation, the `sync` method iterates over regions and calls `get_s3_bucket_list` for each region by changing the `region_name` on the client.
https://github.com/lyft/cartography/blob/6be6f9077265e3604c61b85f3450a313520955b6/cartography/intel/aws/s3.py#L333-L336

https://github.com/lyft/cartography/blob/6be6f9077265e3604c61b85f3450a313520955b6/cartography/intel/aws/s3.py#L16-L19

However I believe this might be unnecessary as a single call to `list_buckets` will return the same set of bucket names regardless of the client `region_name` as they're globally unique.

```python
>>> names = [bucket['Name'] for bucket in boto3.client('s3', region_name='us-east-1').list_buckets()["Buckets"]]
>>> eunames = [bucket['Name'] for bucket in boto3.client('s3', region_name='eu-west-1').list_buckets()["Buckets"]]
>>> names == eunames
True
```

A bucket location constraint can be returned using the `get_bucket_location` API call.

Although it's possible to call `get_bucket_acl` for a bucket say in `us-east-1` when the client `region_name='eu-west-1`.  It might be a case where regions that are opted in might have to set the correct `region_name` the API call is made to.  In the above case for example, we could still be iterating over the set of regions as 'eu-west-1' but querying the bucket ACL for one in `ap-east-1` hence the `IllegalLocationConstraintException`.

I suspect the call to `list_buckets` only needs to be done once, then call `get_bucket_location` for each, if the `LocationConstraint` is not `None` (`us-east-1`, default) perhaps set the client `region_name` to this.  Note there's also a `EU` `LocationConstraint`.

**Comment by achantavy** [comment]
@rsclarke-vgw 
> However I believe this might be unnecessary as a single call to list_buckets will return the same set of bucket names regardless of the client region_name as they're globally unique.

Gotcha.

> A bucket location constraint can be returned using the get_bucket_location API call.

TIL.

>  In the above case for example, we could still be iterating over the set of regions as 'eu-west-1' but querying the bucket ACL for one in ap-east-1 hence the IllegalLocationConstraintException.

Ah, that makes sense.

> I suspect the call to list_buckets only needs to be done once, then call get_bucket_location for each, if the LocationConstraint is not None (us-east-1, default) perhaps set the client region_name to this. 

Thanks! Will give this a try when I get a  chance.  Appreciate the in-depth look.

**Comment by achantavy** [comment]
@rsclarke-vgw I implemented your idea, what do you think?

CC: @marco-lancini

**Comment by achantavy** [comment]
@anewton1980 Mind being our tester again? :D

**Pull request closed without merging**
